### ISSUE TITLE
Conflicts with React native pluggin

### ISSUE THREAD

**Issue by russelRajitha** [kornilova203/matlab-IntelliJ-plugin#58] opened 2019-06-06 06:55 UTC
I installed this plugin and and then react native plugin not working correctly. cli start window opens but run-{platform}  command does not execute. then i removed this and then everything working again. 
IDE : ultimate 2019.1
Platform : MAC High Sierra , Core i7 16GB

**Comment by kornilova203** [comment] 2019-06-06 07:39
Hello @russelRajitha,
Thank you for submitting the issue
It looks like duplicate of #56 

I have just uploaded 0.5.1 version that should fix the problem
Could you please switch to the latest version and comment here if the problem was fixed?

**Closed as completed** 2019-06-07 06:36 UTC
